app/comments/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, HiddenField, SubmitField
from wtforms.validators import Length, DataRequired, ValidationError

from .. import db, models


class CommentForm(FlaskForm):
    body = TextAreaField("Comment", validators=[DataRequired(), Length(1, 500)])
    parent_comment_id = HiddenField()
    submit = SubmitField("Submit")

    def validate_parent_comment_id(self, field):
        if field.data != "":
            if not db.session.query(models.Comment.id).filter_by(id=int(field.data)).scalar():
                raise ValidationError("Invalid parent comment.")

app/comments/__init__.py
from flask import Blueprint

comments = Blueprint("comments", __name__)

from . import views

app/comments/views.py
from datetime import datetime

from flask import redirect, url_for, render_template, abort, flash
from flask_login import current_user, login_required

from . import comments, forms
from .. import db, models
from ..main.views import create_temp_user


def anonymous_warning():
    if not current_user.is_authenticated:
        flash(
            "You are currently not logged in. Any comments you make will publicly display your IP address. \
            Log in or sign up to hide it.",
            "danger")


@comments.route("/<page_type>/<int:page_id>/comments/", methods=["GET", "POST"])
def list_all(page_type: str, page_id: int):
    anonymous_warning()
    if "categories" == page_type:
        cls = models.Category
    elif "tools" == page_type:
        cls = models.Tool
    else:
        abort(404)

    page = cls.query.get_or_404(page_id)

    form = forms.CommentForm()
    if form.is_submitted():
        # Browser renders newlines in textarea as \r\n, convert to just \n
        form.body.data = "\n".join(form.body.data.splitlines())
    if form.validate_on_submit():
        if not current_user.is_authenticated:
            author = create_temp_user()
        else:
            author = current_user

        if form.parent_comment_id.data == "":
            parent_comment_id = None
        else:
            parent_comment_id = form.parent_comment_id.data

        comment = models.Comment(
            body=form.body.data,
            author=author,
            parent_comment_id=parent_comment_id
        )

        if "categories" == page_type:
            comment.parent_category_page_id = page.id
        elif "tools" == page_type:
            comment.parent_tool_page_id = page.id

        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('.list_all', page_type=page_type, page_id=page_id))

    comments = page.comments.filter_by(parent_comment=None)
    return render_template("comments/comments.html",
                           comments=comments,
                           page_type=page_type,
                           page=page,
                           form=form)


@comments.route("/<page_type>/<int:page_id>/comments/<int:comment_id>")
@comments.route("/<page_type>/<int:page_id>/comments/<int:comment_id>/")
def show_single(page_type: str, page_id: int, comment_id: int):
    if "categories" == page_type:
        comment = models.Comment.query.filter_by(id=comment_id, parent_category_page_id=page_id).first_or_404()
        page = comment.parent_category_page
    elif "tools" == page_type:
        comment = models.Comment.query.filter_by(id=comment_id, parent_tool_page_id=page_id).first_or_404()
        page = comment.parent_tool_page
    else:
        abort(404)

    return render_template("comments/comment.html",
                           comment=comment,
                           page=page,
                           page_type=page_type)


@comments.route("/<page_type>/<int:page_id>/comments/<int:comment_id>/delete")
@login_required
def delete(page_type: str, page_id: int, comment_id: int):
    if "categories" == page_type:
        comment = models.Comment.query.filter_by(id=comment_id, parent_category_page_id=page_id).first_or_404()
    elif "tools" == page_type:
        comment = models.Comment.query.filter_by(id=comment_id, parent_tool_page_id=page_id).first_or_404()
    else:
        abort(404)

    if comment.author != current_user:
        abort(403)

    comment.body = "deleted"
    comment.deleted = datetime.utcnow()
    db.session.commit()

    return redirect(url_for(".list_all", page_type=page_type, page_id=page_id))


@comments.route("/<page_type>/<int:page_id>/comments/<int:comment_id>/edit", methods=["GET", "POST"])
@login_required
def edit(page_type: str, page_id: int, comment_id: int):
    anonymous_warning()
    if "categories" == page_type:
        comment = models.Comment.query.filter_by(id=comment_id, parent_category_page_id=page_id).first_or_404()
        page = comment.parent_category_page
    elif "tools" == page_type:
        comment = models.Comment.query.filter_by(id=comment_id, parent_tool_page_id=page_id).first_or_404()
        page = comment.parent_tool_page
    else:
        abort(404)

    if comment.author != current_user:
        abort(401)

    form = forms.CommentForm()
    if form.is_submitted():
        form.body.data = "\n".join(form.body.data.splitlines())
    if form.validate_on_submit():
        comment.body = form.body.data
        comment.edit_time = datetime.utcnow()

        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('.list_all', page_type=page_type, page_id=page_id))

    form.body.data = comment.body

    return render_template("comments/edit_comment.html",
                           form=form,
                           comment=comment,
                           page_type=page_type,
                           page=page)


@comments.route("/<page_type>/<int:page_id>/comments/<int:comment_id>/reply",
                methods=["GET", "POST"])
def reply(page_type: str, page_id: int, comment_id: int):
    anonymous_warning()
    if "categories" == page_type:
        comment = models.Comment.query.filter_by(id=comment_id, parent_category_page_id=page_id).first_or_404()
        page = comment.parent_category_page
    elif "tools" == page_type:
        comment = models.Comment.query.filter_by(id=comment_id, parent_tool_page_id=page_id).first_or_404()
        page = comment.parent_tool_page
    else:
        abort(404)

    form = forms.CommentForm()
    if form.is_submitted():
        form.body.data = "\n".join(form.body.data.splitlines())
    if form.validate_on_submit():
        if not current_user.is_authenticated:
            author = create_temp_user()
        else:
            author = current_user

        comment = models.Comment(
            body=form.body.data,
            author=author,
            parent_comment_id=form.parent_comment_id.data
        )

        if "categories" == page_type:
            comment.parent_category_page_id = page.id
        elif "tools" == page_type:
            comment.parent_tool_page_id = page.id

        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('.list_all', page_type=page_type, page_id=page_id))

    form.parent_comment_id.data = comment.id
    return render_template("comments/reply.html",
                           comment=comment,
                           page=page,
                           page_type=page_type,
                           form=form)

app/templates/comments/_macros.html
{% macro comment_list(page_type, page, comment_list, root) %}
  <ul class="comment-list">
    {% for comment in comment_list recursive %}
      <li>
        {{ single_comment(page_type, page, comment, root) }}
        {% if comment.replies %}
          <ul class="comment-replies">{{ loop(comment.replies) }}</ul>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
{% endmacro %}

{% macro single_comment(page_type, page, comment, root) %}
  <div class="card mb-2">
    <div class="card-body p-2">
      <span>
        <h6 class="mt-1 mb-3">
          <span class="card-subtitle mb-3 text-muted mt-1">
            {% if comment.author.deleted %}
              deleted
            {% else %}
              <a href="{{ url_for("main.user", user_id=comment.author.id) }}">{{ comment.author.username }}</a>
            {% endif %}
          </span>
          <span class="font-light">&nbsp;
            {%- if comment.edit_time -%}
              <i>edited</i> {{ comment.edit_time | timesince }}
            {%- else -%}
              {{ comment.timestamp | timesince }}
            {% endif %}
          </span>
        </h6>
      </span>
      <p class="card-text pl-1 comment-body">
        {{ comment.body }}
      </p>
      <span class="comment-links">
        {% if not comment.deleted %}
          <h6 class="comment-link mr-2">
            <a href="{{ url_for("comments.reply", page_type=page_type, page_id=page.id, comment_id=comment.id) }}"
               class="card-link">Reply</a>
          </h6>
        {% endif %}
        <h6 class="comment-link mr-2">
          <a href="{{ url_for("comments.show_single", page_type=page_type, page_id=page.id, comment_id=comment.id) }}"
             class="card-link">Permalink</a>
        </h6>
        {% if comment.parent_comment and root==comment %}
          <h6 class="comment-link mr-2">
            <a href="{{ url_for("comments.show_single", page_type=page_type, page_id=page.id, comment_id=comment.parent_comment_id) }}"
               class="card-link">Parent</a>
          </h6>
        {% endif %}
        {% if comment.author == current_user %}
          {% if not comment.deleted %}
            <h6 class="comment-link mr-2">
              <a href="{{ url_for("comments.edit", page_type=page_type, page_id=page.id, comment_id=comment.id) }}"
                 class="card-link">Edit</a>
            </h6>
            <h6 class="comment-link">
              <a href="{{ url_for("comments.delete", page_type=page_type, page_id=page.id, comment_id=comment.id) }}"
                 class="card-link comment-delete" data-id="{{ comment.id }}">Delete</a>
            </h6>
          {% endif %}
        {% endif %}
      </span>
    </div>
  </div>
{% endmacro %}

app/templates/comments/comment.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "comments/_macros.html" import comment_list with context %}

{% block title %}Comment{% endblock %}

{% block content %}

  {# Page Title #}
  <h1>
    {%- if page_type == "tools" -%}
      <a href="{{ url_for("main.fetch_tool_page", tool_id=page.id, tool_name=page.slug) }}">{{ page.name }}</a>
    {%- else -%}
      <a href="{{ url_for("main.fetch_category_page", category_id=page.id, category_name=page.slug) }}">{{ page.name }}</a>
    {%- endif -%}
    : <a href="{{ url_for("comments.list_all", page_type=page_type, page_id=page.id) }}">Discussion</a>
  </h1>

  {# Comment List #}
  {{ comment_list(page_type, page, [comment], root=comment) }}

{% endblock %}

app/templates/comments/comments.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "comments/_macros.html" import comment_list with context %}

{% block title %}Comments{% endblock %}
{%- block description -%}
  View the user discussion for {{ page.name }}.
{%- endblock -%}

{% block content %}

  {# Page Title #}
  <h1>
    {%- if page_type == "tools" -%}
      <a href="{{ url_for("main.fetch_tool_page", tool_id=page.id, tool_name=page.slug) }}">{{ page.name }}</a>
    {%- else -%}
      <a href="{{ url_for("main.fetch_category_page", category_id=page.id, category_name=page.slug) }}">{{ page.name }}</a>
    {%- endif -%}
    : Discussion
  </h1>

  {# Comment Form #}
  <div class="row">
    <form class="col-md-6" method="post">
      {{ form.hidden_tag() }}
      {{ wtf.form_errors(form, hiddens="only") }}
      {% set max = 500 %}

      {{ wtf.form_field(form.body, maxlength=max) }}
      <span id="body-count" class="char-count text-muted">{{ max }}</span>
      <div class="d-flex justify-content-end mb-1 mt-1 w-100">
        <input class="btn btn-outline-success form-button" id="submit" name="submit" type="submit" value="Submit">
      </div>
    </form>
  </div>

  {# Comment List #}
  {{ comment_list(page_type, page, comments) }}

{% endblock %}

app/templates/comments/edit_comment.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "comments/_macros.html" import single_comment %}

{% block title %}Edit Comment{% endblock %}

{% block content %}

  {# Page Title #}
  <h1>Edit Comment</h1>

  {# Comment Form #}
  <div class="row">
    <form class="col-md-6" method="post">
      {{ form.hidden_tag() }}
      {{ wtf.form_errors(form, hiddens="only") }}
      {% set max = 500 %}

      {{ wtf.form_field(form.body, maxlength=max) }}
      <span id="body-count" class="char-count text-muted">{{ max }}</span>
      {% include "includes/form_actions.html" %}
    </form>
  </div>

{% endblock %}

app/templates/comments/reply.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "comments/_macros.html" import single_comment %}

{% block title %}Reply{% endblock %}

{% block content %}

  {# Page Title #}
  <h1>Reply to Comment</h1>

  {# Original Comment #}
  {{ single_comment(page_type, page, comment) }}

  {# Comment Form #}
  <div class="row">
    <form class="col-md-6" method="post">
      {{ form.hidden_tag() }}
      {{ wtf.form_errors(form, hiddens="only") }}
      {% set max = 500 %}

      {{ wtf.form_field(form.body, maxlength=max) }}
      <span id="body-count" class="char-count text-muted">{{ max }}</span>
      {% include "includes/form_actions.html" %}
    </form>
  </div>

{% endblock %}